<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WINCTRL-RKIJLJC" name="Default test" tests="2" failures="1" timestamp="2 Feb 2019 15:46:23 GMT" time="18.089" errors="0">
  <testcase name="feature" time="9.312" classname="runner.MainRunner">
    <failure type="cucumber.runtime.CucumberException" message="org.junit.ComparisonFailure: expected:&amp;lt;...nkyouforyourmessage![hhh]&amp;gt; but was:&amp;lt;...nkyouforyourmessage![]&amp;gt;">
      <![CDATA[cucumber.runtime.CucumberException: org.junit.ComparisonFailure: expected:<...nkyouforyourmessage![hhh]> but was:<...nkyouforyourmessage![]>
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.junit.ComparisonFailure: expected:<...nkyouforyourmessage![hhh]> but was:<...nkyouforyourmessage![]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at pageObjects.ContactUs_Page.ConfirmContactUsSubmissionWasSuccesfull(ContactUs_Page.java:61)
	at stepsDefinition.ContactUsSteps.the_information_should_saved_succesfully_to_contact_us_form(ContactUsSteps.java:46)
	at âœ½.Then The information should saved succesfully to contact us form.(contactUS.feature:12)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="7.873" classname="runner.MainRunner"/>
</testsuite> <!-- Default test -->
